/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_fpsstats_free: (a: number, b: number) => void;
export const __wbg_get_fpsstats_average_fps: (a: number) => number;
export const __wbg_get_fpsstats_resolution: (a: number) => number;
export const __wbg_get_fpsstats_subdivisions: (a: number) => number;
export const __wbg_set_fpsstats_average_fps: (a: number, b: number) => void;
export const __wbg_set_fpsstats_resolution: (a: number, b: number) => void;
export const __wbg_set_fpsstats_subdivisions: (a: number, b: number) => void;
export const adjust_to_device_performance: () => number;
export const clear_scene: () => void;
export const get_stats: () => number;
export const main: () => void;
export const next_frame: () => void;
export const play: () => void;
export const print_fluid_info: () => void;
export const run_advection: () => void;
export const run_projection: () => void;
export const run_solve_divergence_for_all: () => void;
export const set_stats: (a: number, b: number) => void;
export const stop: () => void;
export const toggle_playing: () => void;
export const wasm_bindgen_428855bacba1b833___convert__closures_____invoke___web_sys_a9d4660ac2adbb8c___features__gen_PointerEvent__PointerEvent_____: (a: number, b: number, c: any) => void;
export const wasm_bindgen_428855bacba1b833___closure__destroy___dyn_core_9b3796e30d99ddb7___ops__function__FnMut__web_sys_a9d4660ac2adbb8c___features__gen_PointerEvent__PointerEvent____Output_______: (a: number, b: number) => void;
export const wasm_bindgen_428855bacba1b833___convert__closures_____invoke___f64_____: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
